<?php

declare(strict_types=1);

namespace WebiXfBridge;

use WebiXfBridge\BridgeInterface;

enum Settings: string
{
    case enableBridgeSetting      = BridgeInterface::PLUGIN_NAMESPACE . 'enable_bridge';
    case enableBridgeSettingsText = 'Enable Xenforo Bridge';
    case apiUrlSetting            = BridgeInterface::PLUGIN_NAMESPACE . 'api_url';
    case apiUrlSettingText        = 'Url to the Xenforo site to bridge with. (5 - 253 characters)';
    case apiKeySetting            = BridgeInterface::PLUGIN_NAMESPACE . 'api_key';
    case apiKeySettingText        = 'This should be a Super User scoped Api key generated by Xenforo.';
    case nodeIdSetting            = BridgeInterface::PLUGIN_NAMESPACE . 'node_id';
    case nodeIdSettingText        = 'This should be the node_id for the node you want the bridge to post threads in.';
    case xfUserIdSetting          = BridgeInterface::PLUGIN_NAMESPACE . 'xf_user_id';
    case xfUserIdSettingText      = 'Xenforo user_id of the user the bridge should execute as.';
    case requestSchemeSetting     = BridgeInterface::PLUGIN_NAMESPACE . 'request_scheme';
    case requestSchemeSettingText = 'The request scheme used by the Xenforo installation (http or https)';
}
